<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Messaging\MIN.Core.Messaging\MIN.Core.Messaging.csproj" />
    <ProjectReference Include="..\..\Transport\MIN.Core.Transport.NamedPipes\MIN.Core.Transport.UdpSockets\MIN.Core.Transport.UdpSockets.csproj" />
    <ProjectReference Include="..\..\Transport\MIN.Core.Transport.TcpSockets\MIN.Core.Transport.TcpSockets.csproj" />
    <ProjectReference Include="..\MIN.Core.Serialization.Contracts\MIN.Core.Serialization.Contracts.csproj" />
  </ItemGroup>

</Project>
