<Project>

  <!-- Framework properties -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Version>2.2.1.0</Version>
    <EmbedAllSources>true</EmbedAllSources>
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Prefer32Bit>false</Prefer32Bit>
    <Nullable>annotations</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
    <CETCompat>false</CETCompat>
  </PropertyGroup>

  <!-- MIN specific properties -->
  <PropertyGroup>
    <Copyright>2026 CasCade</Copyright>
    <Authors>CasCade Karo4a</Authors>
    <Company>MIN-Corp</Company>
  </PropertyGroup>

  <ItemGroup Condition=" $(MSBuildProjectName.EndsWith('.Tests')) ">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Text.RegularExpressions" />
    <PackageReference Include="Ahatornn.TestGenerator" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Moq" />
  </ItemGroup>
</Project>
