<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <ApplicationIcon>Assets/Icons/logo.ico</ApplicationIcon>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Labs.Gif" />
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="ServiceScan.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
    <PackageReference Include="Xaml.Behaviors.Interactions" />
    <PackageReference Include="Xaml.Behaviors.Interactivity" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DI\MIN.DI\MIN.DI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Cards\Messages\ChatFileImagePreviewMessageView.axaml.cs">
      <DependentUpon>ChatFileImagePreviewMessageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Cards\Messages\ChatVoiceCallMessageView.axaml.cs">
      <DependentUpon>ChatVoiceCallMessageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Cards\Messages\ChatSessionMessageView.axaml.cs">
      <DependentUpon>ChatSessionMessageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Cards\Messages\ChatTextMessageView.axaml.cs">
      <DependentUpon>ChatTextMessageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Cards\Messages\ChatFileMessageView.axaml.cs">
      <DependentUpon>ChatFileMessageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Cards\Messages\SystemChatMessageView.axaml.cs">
      <DependentUpon>SystemChatMessageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\RoomMismatchModal.axaml.cs">
      <DependentUpon>RoomMismatchModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Windows\NotificationWindow.axaml.cs">
      <DependentUpon>NotificationWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\SessionChoosingModal.axaml.cs">
      <DependentUpon>SessionChoosingModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\ParticipantKickModal.axaml.cs">
      <DependentUpon>ParticipantKickModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\LoadingModal.axaml.cs">
      <DependentUpon>LoadingModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\CreateParticipantModal.axaml.cs">
      <DependentUpon>CreateParticipantModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\LogModal.axaml.cs">
      <DependentUpon>LogModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\DirectConnectModal.axaml.cs">
      <DependentUpon>DirectConnectModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\DialogBoxModal.axaml.cs">
      <DependentUpon>DialogBoxModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Modals\CreateRoomModal.axaml.cs">
      <DependentUpon>CreateRoomModal.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Views\Central\ChatView.axaml.cs">
      <DependentUpon>ChatView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Views\Central\DiscoveryView.axaml.cs">
      <DependentUpon>DiscoveryView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Views\Left\MainSideBarView.axaml.cs">
      <DependentUpon>MainSideBarView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Views\Left\SettingsSideBarView.axaml.cs">
      <DependentUpon>SettingsSideBarView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Views\Right\ChatSideBarView.axaml.cs">
      <DependentUpon>ChatSideBarView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Windows\MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
