<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cryptography\MIN.Core.Cryptography.Contracts\MIN.Core.Cryptography.Contracts.csproj" />
    <ProjectReference Include="..\..\Events\MIN.Core.Events\MIN.Core.Events.csproj" />
    <ProjectReference Include="..\..\Messaging\MIN.Core.Messaging\MIN.Core.Messaging.csproj" />
    <ProjectReference Include="..\..\Services\MIN.Core.Services.Contracts\MIN.Core.Services.Contracts.csproj" />
    <ProjectReference Include="..\MIN.Core.Handlers.Contracts\MIN.Core.Handlers.Contracts.csproj" />
  </ItemGroup>

</Project>
