<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Helpers\MIN.Helpers.Contracts\MIN.Helpers.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\MIN.Core.Identity.Contracts\MIN.Core.Identity.Contracts.csproj" />
    <ProjectReference Include="..\MIN.Core.Cryptography.Contracts\MIN.Core.Cryptography.Contracts.csproj" />
  </ItemGroup>

</Project>
